### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by krmaxwell** [kf0jvt/CIFGlue#12]
CIF parser will better understand the following format:

YYYY-MM-DDTHH:MM:SSZ

**Comment by kf0jvt** [comment]
Is that a literal letter T that you want between the day and the hour?  This seems to do the trick: @i.created_at.strftime('%Y-%m-%dT%H:%M:%S%Z') produces "2012-07-03T18:54:04UTC"

I'll make the change as soon as you confirm it.

**Comment by krmaxwell** [comment]
Correct!

**Comment by krmaxwell** [comment]
Also see http://stackoverflow.com/questions/1728404/date-format-yyyy-mm-ddthhmmssz#1728437 because I think it should end in Z, not UTC.

**Comment by kf0jvt** [comment]
OK.  Fixed in 0304524e3c6133e1e6ca19a42b69c77648221468
