### ISSUE TITLE
README needs improvement on how to run

### ISSUE THREAD

**Issue by kf0jvt** [kf0jvt/CIFGlue#14]
I saw an email come through the CIF mailing list that the README file doesn't provide enough information on how to run this application.  Need to improve that by including instructions on creating a postgres user, making sure that the right version of rails is installed, running db:create firing up the server and importing the feeds into CIF.

**Comment by kf0jvt** [comment]
Kyle, I'm giving you the task of writing documentation on how to import the feeds into CIF.

**Comment by krmaxwell** [comment]
Right, as soon as we make sure they're working properly.

**Comment by kf0jvt** [comment]
One thing I'd like to do is give the application a page which spits out the configuration so you can cut/paste into your cif configuration.

**Comment by kf0jvt** [comment]
I added some basic information about how to get the application breathing and then I just said that there are two feeds and how to get them.  That's probably good enough for now.  I really want to tell myself that I knocked out two issues before I go to bed tonight.  Fixed in 772cc6a48c6630cd3061c7bc019527a37c99b126
