### ISSUE TITLE
RSS icon leads to wrong feed

### ISSUE THREAD

**Issue by krmaxwell** [kf0jvt/CIFGlue#15]
When on a specific indicator type page (e.g. /malware), the RSS icon in the upper right still points to the all-indicator feed (indicators.rss) instead of the feed for that page (e.g. malware.rss).

**Comment by kf0jvt** [comment]
Fixed in d6efb0e078c37c15488de38f62891b26ff92d7ae.  Also added a link for the csv view that works.
