### ISSUE TITLE
Only export most recent N indicators

### ISSUE THREAD

**Issue by krmaxwell** [kf0jvt/CIFGlue#36]
Rather than dump the entire list every time, only dump the most recent N indicators (where N is some reasonable integer like 25 or 50). I think that the best approach would be to default N to this reasonable integer while allowing the client to request a parameter to set it higher or lower (e.g. "http://localhost:3000/other.csv?n=1000" or even maybe "http://localhost:3000/other.csv?n=ALL"). This parameter name could be replaced with something more obviously intuitive than n.

**Comment by kf0jvt** [comment]
Added a results parameter which can be put into the parameter string.  To get a csv of the 50 most recent indicators you would use http://server/indicators.csv?results=50.  This can also be used in conjunction with other search fields.  To get 150 most recent malware indicators you could use http://server/indicators?utf8=%E2%9C%93&q%5Bcontent_or_case_or_analyst_or_description_or_alternateid_cont%5D=&q%5Btype_start%5D=MalwareIndicator&q%5Bprivacy_tag_id_eq%5D=&commit=Search&results=150
