### ISSUE TITLE
CSV has unneeded fields

### ISSUE THREAD

**Issue by krmaxwell** [kf0jvt/CIFGlue#37]
The current CSV export has many fields that are empty or unused. All we need for the non-malware indicators are:

ipaddress,case,created_at,indicator_url

which we will map in CIF to:

address,description,detecttime,alternativeid

No double quotes should be exported. Users who find a match in CIF can then click on the link and see the more verbose description and other metadata in CIFGlue.

**Comment by kf0jvt** [comment]
Fixed in technoskald's pull request.
