### ISSUE TITLE
Remove branding

### ISSUE THREAD

**Issue by krmaxwell** [kf0jvt/CIFGlue#5]
Verizon logo on the page should be replaced with something generic but replaceable for specific installations, perhaps as a configurable parameter.

**Comment by kf0jvt** [comment]
I think what I might do is create a model called settings that will hold configurable stuff like this.  Then when someone wants to change it all they have to do is put the correct file into app/assets/images and then update the settings model with the correct filename.

**Comment by kf0jvt** [comment]
Fixed in 2cfc796fb97a99adfeff33b23712659a647f2673
